duelify/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from duelify_app.views import logout_page, discussions,\
    discussion_add_edit, register_page, RegisterSuccess, ChooseCategoryView, CategoryCreate, CategoryUpdate, CategoryDelete,\
    filter_discussions, friends_accept, topics_discuss, voteup_discussion,\
    feedback, side_login, main_login, login_invited, score_reset, faq,\
    punch_edit
from django.views.generic.list import ListView
from duelify_app.models import Ring, Category
from django.views.generic.base import TemplateView
from duelify_app.sitemap import Sitemap


js_info_dict = {
     'packages': ('duelify_app',),
}

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

sitemaps = {
    'discussions':Sitemap,
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'duelify.views.home', name='home'),
    # url(r'^duelify/', include('duelify.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Authentication
    url(r'', include('social_auth.urls')),
    (r'^peyman/', include(admin.site.urls)),            
    (r'^side_login/$', side_login),
    (r'^login/$', main_login),
    (r'^logout/$', logout_page),
    (r'^register/$', register_page),
    (r'^register/success/$', RegisterSuccess.as_view(template_name='registration/register_success.html')),
    
    # Misc
    (r'^i18n/$', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^feedback/$', feedback),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^faq/$', faq),
    (r'^tinymce/', include('tinymce.urls')),
    
    #Password reset
    (r'^password_reset/$','django.contrib.auth.views.password_reset'),
    (r'^password_reset_done/$','django.contrib.auth.views.password_reset_done'),
    (r'^password_reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$','django.contrib.auth.views.password_reset_confirm'),
    (r'^password_reset_complete/$','django.contrib.auth.views.password_reset_complete'),
    
    (r'^$', discussions),    
    #(r'^discussion/(?P<discussion_id>\d+)/$', discussion_display),
    #(r'^discussion/delete/(?P<discussion_id>\d+)/$', discussion_delete),
    #(r'^discussion/edit/(?P<discussion_id>\d+)/$', discussion_add_edit),
    #(r'^discussion/add/', DiscussionAddEdit.as_view()),
    (r'^topics/add/$', discussion_add_edit),
    url(r'^discussion/edit/(?P<ring_id>\d+)/(?P<slug>[-\w\d]+)/$', discussion_add_edit, name='edit-ring'),
    url(r'^discussion/edit/(?P<punch_id>\d+)/$', punch_edit, name='edit-punch'),
    url(r'^topics/discuss/(?P<ring_id>\d+)/(?P<slug>[-\w\d]+)/$', topics_discuss, name='discuss-topic'),
    (r'^vote-up/discussion/(?P<punch_id>\d+)/$', voteup_discussion),
    
    #(r'^topics/search/', discussion_search),
#    url(r'^topics/search/$', ListView.as_view(
#                                           queryset=Ring.objects.order_by('-datetime'), 
#                                           context_object_name='ring_list', 
#                                           template_name='discussions.html'), name='topic-search'),
    #url(r'^topics/search/$', ChooseCategoryView.as_view(), name='topic-search'),
    url(r'^topics/search/$', filter_discussions, name='topic-search'),    
    url(r'^topics/filter/$', ChooseCategoryView.as_view(), name='topic-filter'),    
    url(r'^categories/$', ListView.as_view(model=Category, context_object_name='categories', template_name='categories.html'), name='category-list'),
#    url(r'^category/add/$', CategoryCreate.as_view(), name='author-add'),
#    url(r'^category/edit/(?P<pk>\d+)/$', CategoryUpdate.as_view(), name='author-edit'),
#    url(r'^category/delete/(?P<pk>\d+)/$', CategoryDelete.as_view(), name='author-delete'),
    #(r'^duel/invite/$', duel_invite),
    (r'^duel/accept/(\w+)/$', friends_accept),
    #url(r'^register-invite/$', register_invite, name='register-invite'),
    url(r'^new-users-invited/$', login_invited, name='new-users-invited'),
    url(r'^login-invited/$', login_invited, name='login-invited'),
    url(r'^score-reset/$', score_reset, name='score-reset'),    
    url(r'^signup-error/$', TemplateView.as_view(template_name="error.html"), name='signup-error'),
        
)
urlpatterns += staticfiles_urlpatterns()

duelify_app/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.template.loader import get_template
from django.template.context import Context
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils import timezone
from django.core.exceptions import ValidationError
import datetime
from django.template.defaultfilters import slugify
from django.contrib.sitemaps import ping_google
from tinymce.models import HTMLField
from django.utils.html import strip_tags


def validate_min_100(value):
    raw = strip_tags(value)    
    if raw.__len__()  < 100:
        raise ValidationError(u'Only %s characters? - please express your opinion in more than 100 characters' % raw.__len__())

SIDES = (        
            ('blue',        _(u'Agree')),
            ('red',         _(u'Disagree')),
        )

SIDES_C = (        
            ('blue',        _(u'Blue (agree)')),
            ('red',         _(u'Red (disagree)')),
        )

RULES = (
            ('public',    _(u'Open to anyone to participate')),
            ('personal',  _(u'Limited to only you and your invitee')),
        )

class Category(models.Model):
    category            = models.CharField(_(u'Category'), max_length=35)    
    def __unicode__(self):
        return self.category

    class Meta:
        verbose_name = _(u'Category')
        verbose_name_plural = _(u'Categories')

class Ring(models.Model):
    category        = models.ForeignKey(Category, blank=True, null=True)
    topic           = models.CharField(_(u'Topic'), max_length=50)
    slug            = models.SlugField()
    red             = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='red_users' , blank=True, null=True)
    blue            = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='blue_users', blank=True, null=True)
    datetime        = models.DateTimeField()
    rule            = models.CharField(_(u'Who can participate?'), max_length=8, choices=RULES, default='public')
        
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.topic)
        super(Ring, self).save(*args, **kwargs)
        
    
    def __unicode__(self):
        return self.topic
    class Meta:
        verbose_name = _(u'Ring')
        verbose_name_plural = _(u'Rings')


class Punch(models.Model):
    ring            = models.ForeignKey(Ring)
    speaker         = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='speaker')
    side            = models.CharField(max_length=4, choices=SIDES_C, default='blue', verbose_name=_("On which side are you?"), blank=False)
    discussion      = HTMLField(_(u'Express your opinion'), validators=[validate_min_100])
    datetime        = models.DateTimeField()
    voters          = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name= _("Voters"), null=True, blank=True)
    
    def save(self, *args, **kwargs):    
        super(Punch, self).save(*args, **kwargs) # Call the "real" save() method.
        try:
            ping_google()
        except Exception as ex:
            # Bare 'except' because we could get a variety
            # of HTTP-related exceptions.
            send_mail('ping google failed', ex.message, settings.DEFAULT_FROM_EMAIL, [settings.DEFAULT_FROM_EMAIL])
    
    def get_votes(self):
        return self.voters.count()
    
    def __unicode__(self):        
        return u'%s' % (strip_tags(self.discussion)[slice(0,75)]) 
    class Meta:
        verbose_name = _(u'Punch')
        verbose_name_plural = _(u'Punches')



class DuelInvitation(models.Model):    
    email = models.EmailField()
    code = models.CharField(max_length=20)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL)
    ring = models.ForeignKey(Ring)
    
    def __unicode__(self):
        return u'%s, %s' % (self.sender.last_name, self.email)    

    def send(self):
        subject = _(u'Invitation to a Duel')
        link = '%s/duel/accept/%s/' % (settings.SITE_HOST, self.code)
        template = get_template('registration/invitation_email.txt')
        context = Context({'link': link, 'sender': self.sender.get_full_name(), 'topic':self.ring.topic})
        message = template.render(context)
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.email])
        
        



class MyUserManager(BaseUserManager):
    def create_user(self, email, first_name=None, last_name=None, date_of_birth=None, password=None, location=None, browser=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        
#        if not first_name:
#            raise ValueError('Users must have an first name')
#        
#        if not last_name:
#            raise ValueError('Users must have an last name')

        user = self.model(
            email=MyUserManager.normalize_email(email),
            date_of_birth=date_of_birth or None,
            first_name=first_name or '',
            last_name=last_name or '',
            location=location or '',
            browser=browser or ''
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password, location=None, browser=None, date_of_birth=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        
        if not email:
            raise ValueError('Users must have an email address')
        
        if not first_name:
            raise ValueError('Users must have an first name')
        
        if not last_name:
            raise ValueError('Users must have an last name')
        
        user = self.create_user(email,
            password=password,
            date_of_birth=date_of_birth,
            first_name=first_name,
            last_name=last_name,
            location=location,
            browser=browser
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
  
    email = models.EmailField(verbose_name='email', max_length=255, unique=True, db_index=True,)
    date_of_birth = models.DateField(blank=True, null=True)    
    location = models.CharField(max_length=250, blank=True, null=True)
    browser = models.CharField(max_length=100, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30)   
    score = models.PositiveIntegerField(default=0) 
    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    
    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `Duelify_app`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin    

templates/_paginator.html
{% load i18n %}
{% if show_paginator %}
	<tr id="paginator_tr">
		<td colspan="11">
			<div class="pager cb_pager">
			    <ul>		      
			      	{% if has_prev%}
			      	<li>
			        	<a class="paginator_nav_links" href="{{source}}?page={{ prev_page }}">&laquo; {% trans 'Previous' %}</a>
			        </li>
			      	{% endif %}		      
		          	{% if has_next %}
		          	<li>
		          		<a class="paginator_nav_links" href="{{source}}?page={{ next_page }}">{% trans 'Next' %} &raquo;</a>
		          	</li>
			      	{% endif %}		      		      
			    </ul>
			    <div>
		    		{% blocktrans with p=page ps=pages%}Page {{ p }} of {{ ps }}{% endblocktrans %}
		    	</div>
		   	</div>
   	  	</td>
	</tr>		    
{% endif %}

templates/categories.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="row-fluid">
  	{% for category in categories %}
        <div class="span4">
          <h2>{{category.category}}</h2>
          
          <p><a class="btn" href="#">{% trans 'View &amp; Vote &raquo; ' %}</a></p>
        </div><!--/span-->    
    {% endfor %}        
</div><!--/row-->
{% endblock %}

templates/category.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load i18n %}
{% load get_button_title %}
{% block content %}
<ul class="breadcrumb">
	<li><a id="back2contacts" href="/">{% trans 'Home' %}</a> <span class="divider">></span></li>
	<li class="active">{% trans 'Search for topics' %}</li>	    	
</ul>

<div class="row-fluid">
    <form id="save_add_form" method="post" action=".">
		{% csrf_token %}
		<div class="parent">	    	
			<div class="well well-large">	
				{% show_row_div_below_error form.category|attr:"class:big-input"  %}
				{% show_row_div_below_error form.show_open_topics %}             	         
																		
				<a id="contact_cancel_btn" href="/" class="btn btn-large cb-float-to-right">{% trans 'Back' %}</a> 
				<button type="submit" id="add_topic" autocomplete="off" class="btn btn-primary btn-large cb-float-to-right">{% trans 'Filter' %}</button>			   			
			</div>
		</div>    
	</form>                   
</div>
<div class="row-fluid">
  	{% for ring in rings %}
        <div class="span4">
          <h2>{{ring.topic}}</h2>
          <p>{% trans 'Category' %}: {{ring.category}}</p>
          {% if ring.punch_set.all %}
          	<p>{{ ring.punch_set.all.0.discussion|slice:":100" }}...</p>
          {% endif %}          
          <p><a class="btn discuss_btn" href="/topics/discuss/{{ring.pk}}/{{ring.slug}}">{% get_button_title ring user %}</a></p>
        </div><!--/span-->      
    {% endfor %}      
</div><!--/row-->
{% include '_paginator.html' %}

{% endblock %}

templates/discuss_topic.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load i18n %}
{% load get_votes_for_punch %}
{% block meta_title %}{{ring.topic}}{% endblock %}
{% block meta_desc %}{{ ring.punch_set.all.0.discussion|striptags|slice:":150" }}{% endblock %}
{% block content %}
<ul class="breadcrumb">
	<li><a id="back2contacts" href="/">{% trans 'Home' %}</a> <span class="divider">></span></li>
	<li class="active">{{template_title}}</li>	    	
</ul>

<div class="row-fluid">    
		<div class="parent">	    	
			<div>	
				<h2>{{ring.topic}}</h2>
				<h5>{% trans 'Category:' %} {{ring.category}}</h5>
				<h4>{{winner_sofar}} <span class="well-{{winner_color}}">{{winner}}</span></h4>				
				{% for punch in punches %}
					<div class="row">
						{% if punch.side = 'blue' %}						
							<div class="block_inline cb-float-to-left">
								{{punch.speaker.get_full_name}}
								{% if punch.speaker == user %}
									<a class="btn btn-link cb-float-to-right punch-edit" href='/discussion/edit/{{punch.pk}}/'>{% trans 'Edit' %}</a>
								{% endif %}
								<div class="well well-blue well-large">
									<p>{{punch.discussion|safe}}</p>
								</div>
							</div>
							
							<div class="block_inline cb-float-to-left">
								{% if punch.speaker != user %}
									<a class="btn {% get_votes_for_punch punch user %}" href="/vote-up/discussion/{{punch.pk}}"><i class="icon-thumbs-up icon-large"/></i></a>
								{% endif %}
								
								{% trans 'Votes' %}: {{punch.get_votes}}
							</div>							
						{% endif %}
	
						{% if punch.side = 'red' %}
							<div class="block_inline cb-float-to-right">
								{{punch.speaker.get_full_name}}
								{% if punch.speaker == user %}
									<a class="btn btn-link cb-float-to-right punch-edit" href='/discussion/edit/{{punch.pk}}/'>{% trans 'Edit' %}</a>
								{% endif %}
								<div class="well well-red well-large">
									<p>{{punch.discussion|safe}}</p>
								</div>
							</div>
							
							<div class="block_inline cb-float-to-right">
								{% if punch.speaker != user %}
									<a class="btn {% get_votes_for_punch punch user %}" href="/vote-up/discussion/{{punch.pk}}"><i class="icon-thumbs-up icon-large"/></i></a>
								{% endif %}
								
								{% trans 'Votes' %}: {{punch.get_votes}}
							</div>
							
						{% endif %}
					</div>
				{% endfor %}				
				{% if user.is_authenticated and punch_form %}					
					<form class="{% if punch.side = 'red' %}cb-float-to-right{% else %}cb-float-to-left{% endif %}"  id="save_add_form" method="post" action=".">
						{% csrf_token %}
						{% if not is_continue %}
							{% show_row_div_below_error punch_form.side  %}
						{% endif %}
						{% show_row_div_below_error punch_form.discussion  %}			
						<a id="contact_cancel_btn" href="/" class="btn btn-large cb-float-to-right">{% trans 'Cancel' %}</a> 
						<button type="submit" id="add_topic" autocomplete="off" class="btn btn-primary btn-large cb-float-to-right">{% trans 'Add Your Opinion' %}</button>
					</form> 		
				{% endif %}	   			
			</div>
		</div>       
    	            
</div>

{% endblock %}

templates/error.html
There was an error
{{error}}
{{ValueError}}
{{message}}
{{ request.GET.message }}

templates/feedback.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load i18n %}
{% block content %}
<div class="row-fluid">
	<div class="well well-small well-auto">
		<form id="feedback_form" method="post" action=".">		
			{% csrf_token %}
			<div>
				{% if form.feedback.required %}<label for="{{ form_field.auto_id }}" class="cb_inline_block" rel="tooltip" title="Required Field">{{form.feedback.label}}: *</label>{%else%}<label for="{{ form.feedback.auto_id }}">{{form.feedback.label}}:</label>{% endif %}
			</div>			
			{{form.feedback}}
			<div class="row field field_error">
				<div class="cb-float-to-right">
					{{form.feedback.errors}}
				</div>
			</div>			 
			<button type="submit" id="feedback_btn" autocomplete="off" class="btn btn-primary btn-large cb-float-to-left">{% trans 'Send Feedback' %}</button>
			<a id="feedback_cancel_btn" href="/" class="btn btn-large cb-float-to-left">{% trans 'Cancel' %}</a>
		</form>
	</div>
</div>
{% endblock %}

templates/main.html
{% extends "base.html" %}
{% load i18n %}
{% load get_button_title %}
{% block meta_title %}Duelify | Duel Your Friends &amp; Foes{% endblock %}
{% block content %}
<div id="myCarousel" class="carousel slide">
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
		<li data-target="#myCarousel" data-slide-to="3"></li>
		
	</ol>
	<!-- Carousel items -->
	<div class="carousel-inner">		
		<div class="item active">
			<div class="hero-unit">			    
			    <h1>{% trans 'A dueling ground to fight out opinions.'  %} <i class="icon-globe icon-2x pull-right"> </i></h1>
				<h2>{% trans 'And the audience votes for which side is right.' %}</h2>
				<h3>{% trans 'Start a topic now!' %}</h3>
			    {% if user.is_authenticated %}
			    	<p class="padding_by_10"><a href="/topics/add/" class="btn btn-success btn-large">{% trans 'Start a topic' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>
			    {% else %}
			    	<p class="padding_by_10"><a href="/register/" class="btn btn-primary btn-large">{% trans 'Sign up' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>		            	
			    {% endif %}		                
			</div> 
		</div>
		<div class="item">
			<div class="hero-unit">
			    <h1>{% trans 'Endless discussions?'  %} <i class="icon-tint icon-2x pull-right"> </i></h1>
			    <h2>{% trans 'Duel your friend or foe into a public discussion!'  %}</h2>			    
				<h3>{% trans 'And let the audience vote for who is right!' %}</h3>
			    {% if user.is_authenticated %}
			    	<p class="padding_by_10"><a href="/topics/add/" class="btn btn-success btn-large">{% trans 'Start a topic' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>
			    {% else %}
			    	<p class="padding_by_10"><a href="/register/" class="btn btn-primary btn-large">{% trans 'Sign up' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>		            	
			    {% endif %}		                
			</div>			 
		</div>		
	</div>
	<!-- Carousel nav -->
	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

{% for ring in all_rings %}
	{% if forloop.first %}<div class="row-fluid">{% endif %}
	{% if forloop.counter0|divisibleby:3 %}
		</div><div class="row-fluid">
	{% endif %}
    <div class="span4">
      <h3>{{ring.topic}}</h2>
      <p>{% trans 'Category' %}: {{ring.category}}</p>
      {% if ring.punch_set.all %}
      	<p>{{ ring.punch_set.all.0.discussion|striptags|slice:":100" }}...</p>
      {% endif %}  
      <p><a class="btn discuss_btn" href="/topics/discuss/{{ring.pk}}/{{ring.slug}}">{% get_button_title ring user %}</a></p>
    </div><!--/span-->
    {% if forloop.last %}</div>{% endif %}    
{% endfor %}        

{% endblock %}

templates/sidebar_top10.html
{% load i18n %}
{% load get_score_for_user %}
<li class="nav-header"><!-- <i class="icon-trophy icon-large"></i> -->{% trans 'Top Ten Contributers' %}</li>

{% get_top10_users %}

templates/top6_topics.html
{% extends "base.html" %}
{% load i18n %}
{% load get_button_title %}
{% block content %}
<div id="myCarousel" class="carousel slide">
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="3"></li>
		
	</ol>
	<!-- Carousel items -->
	<div class="carousel-inner">
		<div class="active item">
			<div class="hero-unit">			    
			    <h1>{% trans 'What are you passionate about?'  %} <i class="icon-globe icon-2x pull-right"> </i></h1>
			    <h3>{% trans 'Is there a topic you love and like to share with the world?' %}</h3>
				<h3>{% trans 'Simply do it and see if the audience votes for your idea!' %}</h3>
			    {% if user.is_authenticated %}
			    	<p class="padding_by_10"><a href="/topics/add/" class="btn btn-success btn-large">{% trans 'Start a topic' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>
			    {% else %}
			    	<p class="padding_by_10"><a href="/register/" class="btn btn-primary btn-large">{% trans 'Sign up' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>		            	
			    {% endif %}		                
			</div> 
		</div>
		<div class="item">
			<div class="hero-unit">			    
			    <h1>{% trans 'Duel your friends &amp; foes'  %} <i class="icon-tint icon-2x pull-right"> </i></h1>
			    <h3>{% trans 'Is there a topic you love to discuss with a friend or foe?' %}</h3>
				<h3>{% trans 'Duel them and let the audience vote for who is right!' %}</h3>
			    {% if user.is_authenticated %}
			    	<p class="padding_by_10"><a href="/topics/add/" class="btn btn-success btn-large">{% trans 'Start a topic' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>
			    {% else %}
			    	<p class="padding_by_10"><a href="/register/" class="btn btn-primary btn-large">{% trans 'Sign up' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>		            	
			    {% endif %}		                
			</div>			 
		</div>
		<div class="item">
			<div class="hero-unit">			    
			    <h1>{% trans 'Collect points when up-voted'  %} <i class="icon-trophy icon-2x pull-right"> </i></h1>
			    <h3>{% trans 'Gain honor badges and achievements' %}</h3>
				<h3>{% trans 'Experience a new platform to exchange ideas about anything' %}</h3>
			    {% if user.is_authenticated %}
			    	<p class="padding_by_10"><a href="/topics/add/" class="btn btn-success btn-large">{% trans 'Start a topic' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>
			    {% else %}
			    	<p class="padding_by_10"><a href="/register/" class="btn btn-primary btn-large">{% trans 'Sign up' %} &raquo;</a><a href="topics/search/" class="btn btn-large margin_to_left">{% trans 'Find a topic' %} &raquo;</a></p>		            	
			    {% endif %}		                
			</div>			 
		</div>		
	</div>
	<!-- Carousel nav -->
	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<div class="row-fluid">
  	{% for ring in top3rings %}
        <div class="span4">
          <h3>{{ring.topic}}</h2>
          <p>{% trans 'Category' %}: {{ring.category}}</p>
          {% if ring.punch_set.all %}
          	<p>{{ ring.punch_set.all.0.discussion|slice:":100" }}...</p>
          {% endif %}  
          <p><a class="btn discuss_btn" href="/topics/discuss/{{ring.pk}}/{{ring.slug}}">{% get_button_title ring user %}</a></p>
        </div><!--/span-->      
    {% endfor %}      
</div><!--/row-->
<div class="row-fluid">
  	{% for ring in top3_6rings %}
        <div class="span4">
          <h3>{{ring.topic}}</h2>
          <p>{% trans 'Category' %}: {{ring.category}}</p>
          {% if ring.punch_set.all %}
          	<p>{{ ring.punch_set.all.0.discussion|slice:":100" }}...</p>
          {% endif %}  
          <p><a class="btn discuss_btn" href="/topics/discuss/{{ring.pk}}/{{ring.slug}}">{% get_button_title ring user %}</a></p>
        </div><!--/span-->    
    {% endfor %}        
</div><!--/row-->
{% endblock %}